/* Auto-generated by tools/generate_steno_dictionary.py. */
/* SPDX-License-Identifier: MIT */

#include <stddef.h>
#include <stdint.h>
#include <dt-bindings/zmk/keys.h>
#include <cornix_steno/dictionary.h>
#include <cornix_steno/roles.h>

/* 그런 */
static const uint32_t dict_seq_00[] = { R, M, F, J, S };
/* 다른 */
static const uint32_t dict_seq_01[] = { E, K, F, M, S };
/* 같은 */
static const uint32_t dict_seq_02[] = { R, K, X, D, M, S };
/* 다시 */
static const uint32_t dict_seq_03[] = { E, K, T, L };
/* 조금 */
static const uint32_t dict_seq_04[] = { W, H, R, M, A };
/* 그렇게 */
static const uint32_t dict_seq_05[] = { R, M, F, J, G, R, P };
/* 이런 */
static const uint32_t dict_seq_06[] = { D, L, F, J, S };
/* 그리고 */
static const uint32_t dict_seq_07[] = { R, M, F, L, R, H };
/* 하지만 */
static const uint32_t dict_seq_08[] = { G, K, W, L, A, K, S };
/* 이렇게 */
static const uint32_t dict_seq_09[] = { D, L, F, J, G, R, P };
/* 함께 */
static const uint32_t dict_seq_10[] = { G, K, A, LS(R), P };
/* 없이 */
static const uint32_t dict_seq_11[] = { D, J, Q, T, D, L };
/* 커다란 */
static const uint32_t dict_seq_12[] = { Z, J, E, K, F, K, S };
/* 이미 */
static const uint32_t dict_seq_13[] = { D, L, A, L };
/* 전부 */
static const uint32_t dict_seq_14[] = { W, J, S, Q, N };
/* 너무 */
static const uint32_t dict_seq_15[] = { S, J, A, N };
/* 말했다 */
static const uint32_t dict_seq_16[] = { A, K, F, G, O, LS(T), E, K };
/* 그러자 */
static const uint32_t dict_seq_17[] = { R, M, F, J, W, K };
/* 완전히 */
static const uint32_t dict_seq_18[] = { D, H, K, S, W, J, S, G, L };
/* 그대로 */
static const uint32_t dict_seq_19[] = { R, M, E, O, F, H };
/* 아닌 */
static const uint32_t dict_seq_20[] = { D, K, S, L, S };
/* 바로 */
static const uint32_t dict_seq_21[] = { Q, K, F, H };
/* 점점 */
static const uint32_t dict_seq_22[] = { W, J, A, W, J, A };
/* 그래도 */
static const uint32_t dict_seq_23[] = { R, M, F, O, E, H };
/* 계속해서 */
static const uint32_t dict_seq_24[] = { R, LS(P), T, H, R, G, O, T, J };
/* 빠르게 */
static const uint32_t dict_seq_25[] = { LS(Q), K, F, M, R, P };
/* 천천히 */
static const uint32_t dict_seq_26[] = { C, J, S, C, J, S, G, L };
/* 가만히 */
static const uint32_t dict_seq_27[] = { R, K, A, K, S, G, L };
/* 결국 */
static const uint32_t dict_seq_28[] = { R, U, F, R, N, R };
/* 곧바로 */
static const uint32_t dict_seq_29[] = { R, H, E, Q, K, F, H };
/* 그때 */
static const uint32_t dict_seq_30[] = { R, M, LS(E), O };
/* 잠시 */
static const uint32_t dict_seq_31[] = { W, K, A, T, L };
/* 그럼 */
static const uint32_t dict_seq_32[] = { R, M, F, J, A };
/* 정말로 */
static const uint32_t dict_seq_33[] = { W, J, D, A, K, F, F, H };
/* 때문에 */
static const uint32_t dict_seq_34[] = { LS(E), O, A, N, S, D, P };
/* 조용히 */
static const uint32_t dict_seq_35[] = { W, H, D, Y, D, G, L };
/* 그러면 */
static const uint32_t dict_seq_36[] = { R, M, F, J, A, U, S };
/* 동시에 */
static const uint32_t dict_seq_37[] = { E, H, D, T, L, D, P };
/* 오히려 */
static const uint32_t dict_seq_38[] = { D, H, G, L, F, U };
/* 갑자기 */
static const uint32_t dict_seq_39[] = { R, K, Q, W, K, R, L };
/* 서서히 */
static const uint32_t dict_seq_40[] = { T, J, T, J, G, L };
/* 그럼에도 */
static const uint32_t dict_seq_41[] = { R, M, F, J, A, D, P, E, H };
/* 아니면 */
static const uint32_t dict_seq_42[] = { D, K, S, L, A, U, S };
/* 순식간에 */
static const uint32_t dict_seq_43[] = { T, N, S, T, L, R, R, K, S, D, P };
/* 그러니까 */
static const uint32_t dict_seq_44[] = { R, M, F, J, S, L, LS(R), K };
/* 그렇다면 */
static const uint32_t dict_seq_45[] = { R, M, F, J, G, E, K, A, U, S };
/* 그런데 */
static const uint32_t dict_seq_46[] = { R, M, F, J, S, E, P };
/* 말 없이 */
static const uint32_t dict_seq_47[] = { A, K, F, SPACE, D, J, Q, T, D, L };
/* 잠시 후 */
static const uint32_t dict_seq_48[] = { W, K, A, T, L, SPACE, G, N };
/* 그러나 */
static const uint32_t dict_seq_49[] = { R, M, F, J, S, K };
/* 그렇군 */
static const uint32_t dict_seq_50[] = { R, M, F, J, G, R, N, S };
/* 바라봤다 */
static const uint32_t dict_seq_51[] = { Q, K, F, K, Q, H, K, LS(T), E, K };
/* 한숨을 쉬었다 */
static const uint32_t dict_seq_52[] = { G, K, S, T, N, A, D, M, F, SPACE, T, N, L, D, J, LS(T), E, K };
/* 자신도 모르게 */
static const uint32_t dict_seq_53[] = { W, K, T, L, S, E, H, SPACE, A, H, F, M, R, P };
/* 고개를 끄덕였다 */
static const uint32_t dict_seq_54[] = { R, H, R, O, F, M, F, SPACE, LS(R), M, E, J, R, D, U, LS(T), E, K };
/* 눈을 크게 떴다 */
static const uint32_t dict_seq_55[] = { S, N, S, D, M, F, SPACE, Z, M, R, P, SPACE, LS(E), J, LS(T), E, K };
/* 침을 꿀꺽 삼켰다 */
static const uint32_t dict_seq_56[] = { C, L, A, D, M, F, SPACE, LS(R), N, F, LS(R), J, R, SPACE, T, K, A, Z, U, LS(T), E, K };
/* 근데 */
static const uint32_t dict_seq_57[] = { R, M, S, E, P };
/* 였다 */
static const uint32_t dict_seq_58[] = { D, U, LS(T), E, K };
/* 했다 */
static const uint32_t dict_seq_59[] = { G, O, LS(T), E, K };
/* 으면 */
static const uint32_t dict_seq_60[] = { D, M, A, U, S };

static const struct cornix_steno_dictionary_entry entries[] = {
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_00, .key_count = (uint16_t)(sizeof(dict_seq_00) / sizeof(dict_seq_00[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_F_D) | CST_ROLE_BIT(CST_R_I_R)), .keys = dict_seq_01, .key_count = (uint16_t)(sizeof(dict_seq_01) / sizeof(dict_seq_01[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_NG)), .keys = dict_seq_02, .key_count = (uint16_t)(sizeof(dict_seq_02) / sizeof(dict_seq_02[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_F_D) | CST_ROLE_BIT(CST_R_I_S)), .keys = dict_seq_03, .key_count = (uint16_t)(sizeof(dict_seq_03) / sizeof(dict_seq_03[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_04, .key_count = (uint16_t)(sizeof(dict_seq_04) / sizeof(dict_seq_04[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_05, .key_count = (uint16_t)(sizeof(dict_seq_05) / sizeof(dict_seq_05[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_06, .key_count = (uint16_t)(sizeof(dict_seq_06) / sizeof(dict_seq_06[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_07, .key_count = (uint16_t)(sizeof(dict_seq_07) / sizeof(dict_seq_07[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_H) | CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_08, .key_count = (uint16_t)(sizeof(dict_seq_08) / sizeof(dict_seq_08[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_09, .key_count = (uint16_t)(sizeof(dict_seq_09) / sizeof(dict_seq_09[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_H) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_10, .key_count = (uint16_t)(sizeof(dict_seq_10) / sizeof(dict_seq_10[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_NG)), .keys = dict_seq_11, .key_count = (uint16_t)(sizeof(dict_seq_11) / sizeof(dict_seq_11[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_KH) | CST_ROLE_BIT(CST_R_F_D) | CST_ROLE_BIT(CST_R_I_R)), .keys = dict_seq_12, .key_count = (uint16_t)(sizeof(dict_seq_12) / sizeof(dict_seq_12[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_13, .key_count = (uint16_t)(sizeof(dict_seq_13) / sizeof(dict_seq_13[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_B)), .keys = dict_seq_14, .key_count = (uint16_t)(sizeof(dict_seq_14) / sizeof(dict_seq_14[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_N) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_15, .key_count = (uint16_t)(sizeof(dict_seq_15) / sizeof(dict_seq_15[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_M) | CST_ROLE_BIT(CST_R_F_H) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_16, .key_count = (uint16_t)(sizeof(dict_seq_16) / sizeof(dict_seq_16[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_J)), .keys = dict_seq_17, .key_count = (uint16_t)(sizeof(dict_seq_17) / sizeof(dict_seq_17[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_I_H)), .keys = dict_seq_18, .key_count = (uint16_t)(sizeof(dict_seq_18) / sizeof(dict_seq_18[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_19, .key_count = (uint16_t)(sizeof(dict_seq_19) / sizeof(dict_seq_19[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_N)), .keys = dict_seq_20, .key_count = (uint16_t)(sizeof(dict_seq_20) / sizeof(dict_seq_20[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_B) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_21, .key_count = (uint16_t)(sizeof(dict_seq_21) / sizeof(dict_seq_21[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_J)), .keys = dict_seq_22, .key_count = (uint16_t)(sizeof(dict_seq_22) / sizeof(dict_seq_22[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_23, .key_count = (uint16_t)(sizeof(dict_seq_23) / sizeof(dict_seq_23[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_F_G) | CST_ROLE_BIT(CST_R_I_S) | CST_ROLE_BIT(CST_R_I_H) | CST_ROLE_BIT(CST_R_F_S)), .keys = dict_seq_24, .key_count = (uint16_t)(sizeof(dict_seq_24) / sizeof(dict_seq_24[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_DOUBLE) | CST_ROLE_BIT(CST_R_I_B) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_25, .key_count = (uint16_t)(sizeof(dict_seq_25) / sizeof(dict_seq_25[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_CH) | CST_ROLE_BIT(CST_R_F_H)), .keys = dict_seq_26, .key_count = (uint16_t)(sizeof(dict_seq_26) / sizeof(dict_seq_26[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_M) | CST_ROLE_BIT(CST_R_I_H)), .keys = dict_seq_27, .key_count = (uint16_t)(sizeof(dict_seq_27) / sizeof(dict_seq_27[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_28, .key_count = (uint16_t)(sizeof(dict_seq_28) / sizeof(dict_seq_28[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_B) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_29, .key_count = (uint16_t)(sizeof(dict_seq_29) / sizeof(dict_seq_29[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_30, .key_count = (uint16_t)(sizeof(dict_seq_30) / sizeof(dict_seq_30[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_S)), .keys = dict_seq_31, .key_count = (uint16_t)(sizeof(dict_seq_31) / sizeof(dict_seq_31[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_32, .key_count = (uint16_t)(sizeof(dict_seq_32) / sizeof(dict_seq_32[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_M) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_33, .key_count = (uint16_t)(sizeof(dict_seq_33) / sizeof(dict_seq_33[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_I_M) | CST_ROLE_BIT(CST_R_F_NG)), .keys = dict_seq_34, .key_count = (uint16_t)(sizeof(dict_seq_34) / sizeof(dict_seq_34[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_I_H)), .keys = dict_seq_35, .key_count = (uint16_t)(sizeof(dict_seq_35) / sizeof(dict_seq_35[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_36, .key_count = (uint16_t)(sizeof(dict_seq_36) / sizeof(dict_seq_36[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_I_S) | CST_ROLE_BIT(CST_R_F_NG)), .keys = dict_seq_37, .key_count = (uint16_t)(sizeof(dict_seq_37) / sizeof(dict_seq_37[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_H) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_38, .key_count = (uint16_t)(sizeof(dict_seq_38) / sizeof(dict_seq_38[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_J)), .keys = dict_seq_39, .key_count = (uint16_t)(sizeof(dict_seq_39) / sizeof(dict_seq_39[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_S) | CST_ROLE_BIT(CST_R_F_S) | CST_ROLE_BIT(CST_R_I_H)), .keys = dict_seq_40, .key_count = (uint16_t)(sizeof(dict_seq_40) / sizeof(dict_seq_40[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_F_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_I_D)), .keys = dict_seq_41, .key_count = (uint16_t)(sizeof(dict_seq_41) / sizeof(dict_seq_41[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_N) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_42, .key_count = (uint16_t)(sizeof(dict_seq_42) / sizeof(dict_seq_42[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_S) | CST_ROLE_BIT(CST_R_F_S) | CST_ROLE_BIT(CST_R_F_G) | CST_ROLE_BIT(CST_R_I_NG)), .keys = dict_seq_43, .key_count = (uint16_t)(sizeof(dict_seq_43) / sizeof(dict_seq_43[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_I_N) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_44, .key_count = (uint16_t)(sizeof(dict_seq_44) / sizeof(dict_seq_44[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_D) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_45, .key_count = (uint16_t)(sizeof(dict_seq_45) / sizeof(dict_seq_45[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_46, .key_count = (uint16_t)(sizeof(dict_seq_46) / sizeof(dict_seq_46[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_M) | CST_ROLE_BIT(CST_R_F_NG)), .keys = dict_seq_47, .key_count = (uint16_t)(sizeof(dict_seq_47) / sizeof(dict_seq_47[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_S) | CST_ROLE_BIT(CST_R_I_H)), .keys = dict_seq_48, .key_count = (uint16_t)(sizeof(dict_seq_48) / sizeof(dict_seq_48[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_I_N)), .keys = dict_seq_49, .key_count = (uint16_t)(sizeof(dict_seq_49) / sizeof(dict_seq_49[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_50, .key_count = (uint16_t)(sizeof(dict_seq_50) / sizeof(dict_seq_50[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_B) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_B) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_51, .key_count = (uint16_t)(sizeof(dict_seq_51) / sizeof(dict_seq_51[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_H) | CST_ROLE_BIT(CST_R_I_S) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_S) | CST_ROLE_BIT(CST_R_I_D)), .keys = dict_seq_52, .key_count = (uint16_t)(sizeof(dict_seq_52) / sizeof(dict_seq_52[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_I_S) | CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_F_M) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_53, .key_count = (uint16_t)(sizeof(dict_seq_53) / sizeof(dict_seq_53[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_G) | CST_ROLE_BIT(CST_R_I_DOUBLE) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_54, .key_count = (uint16_t)(sizeof(dict_seq_54) / sizeof(dict_seq_54[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_N) | CST_ROLE_BIT(CST_R_I_KH) | CST_ROLE_BIT(CST_R_F_G) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_55, .key_count = (uint16_t)(sizeof(dict_seq_55) / sizeof(dict_seq_55[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_F_CH) | CST_ROLE_BIT(CST_R_I_DOUBLE) | CST_ROLE_BIT(CST_R_I_KH) | CST_ROLE_BIT(CST_R_I_D)), .keys = dict_seq_56, .key_count = (uint16_t)(sizeof(dict_seq_56) / sizeof(dict_seq_56[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_57, .key_count = (uint16_t)(sizeof(dict_seq_57) / sizeof(dict_seq_57[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_58, .key_count = (uint16_t)(sizeof(dict_seq_58) / sizeof(dict_seq_58[0])) },
    { .bank = 1, .role_mask = (CST_ROLE_BIT(CST_R_I_H) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_59, .key_count = (uint16_t)(sizeof(dict_seq_59) / sizeof(dict_seq_59[0])) },
    { .bank = 2, .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_60, .key_count = (uint16_t)(sizeof(dict_seq_60) / sizeof(dict_seq_60[0])) },
};

const struct cornix_steno_dictionary_entry *
cornix_steno_dictionary_lookup(uint8_t bank, uint64_t role_mask) {
    for (size_t i = 0; i < sizeof(entries) / sizeof(entries[0]); i++) {
        if (entries[i].bank == bank && entries[i].role_mask == role_mask) {
            return &entries[i];
        }
    }
    return NULL;
}

size_t cornix_steno_dictionary_count(void) {
    return sizeof(entries) / sizeof(entries[0]);
}
