/* Auto-generated by tools/generate_steno_quick.py. */
/* SPDX-License-Identifier: MIT */

#include <stddef.h>
#include <stdint.h>
#include <dt-bindings/zmk/keys.h>
#include <cornix_steno/quick.h>
#include <cornix_steno/roles.h>


static const struct cornix_steno_quick_entry entries[] = {
    { .slot = "QUICK_L_LEFT", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_EU) | CST_ROLE_BIT(CST_R_V_O) | CST_ROLE_BIT(CST_R_V_U)), .keys = NULL, .key_count = 0 },
    { .slot = "QUICK_R_RIGHT", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_A) | CST_ROLE_BIT(CST_R_V_I) | CST_ROLE_BIT(CST_R_V_EO)), .keys = NULL, .key_count = 0 },
    { .slot = "QUICK_L_RIGHT", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_A) | CST_ROLE_BIT(CST_R_V_EO) | CST_ROLE_BIT(CST_R_V_I)), .keys = NULL, .key_count = 0 },
    { .slot = "QUICK_R_LEFT", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_O) | CST_ROLE_BIT(CST_R_V_U) | CST_ROLE_BIT(CST_R_V_EU)), .keys = NULL, .key_count = 0 },
};

const struct cornix_steno_quick_entry *cornix_steno_quick_lookup(uint64_t role_mask) {
    for (size_t i=0; i<sizeof(entries)/sizeof(entries[0]); i++)
        if (entries[i].role_mask == role_mask) return &entries[i];
    return NULL;
}

size_t cornix_steno_quick_count(void) { return sizeof(entries)/sizeof(entries[0]); }
