/* Auto-generated by tools/generate_steno_dictionary.py. */
/* Canonical exact masks: ABBR_L/R distinct; one VEXT side = AB2. */
/* SPDX-License-Identifier: MIT */

#include <stddef.h>
#include <stdint.h>
#include <dt-bindings/zmk/keys.h>
#include <cornix_steno/dictionary.h>
#include <cornix_steno/roles.h>

/* BASIC_JEOMJEOM | basic_word | 점점 */
static const uint32_t dict_seq_00[] = { W, J, A, W, J, A };
/* BASIC_JINJJA | basic_word | 진짜 */
static const uint32_t dict_seq_01[] = { W, L, S, LS(W), K };
/* BASIC_GYEOLGUK | basic_word | 결국 */
static const uint32_t dict_seq_02[] = { R, U, F, R, N, R };
/* BASIC_GEUREOKE | basic_word | 그렇게 */
static const uint32_t dict_seq_03[] = { R, M, F, J, G, R, P };
/* BASIC_GEUREOTGUN | basic_word | 그렇군 */
static const uint32_t dict_seq_04[] = { R, M, F, J, G, R, N, S };
/* BASIC_GEUREON | basic_word | 그런 */
static const uint32_t dict_seq_05[] = { R, M, F, J, S };
/* BASIC_GEUREOM | basic_word | 그럼 */
static const uint32_t dict_seq_06[] = { R, M, F, J, A };
/* BASIC_GEURAEDO | basic_word | 그래도 */
static const uint32_t dict_seq_07[] = { R, M, F, O, E, H };
/* BASIC_GEUREONDE | basic_word | 그런데 */
static const uint32_t dict_seq_08[] = { R, M, F, J, S, E, P };
/* BASIC_GEUREOMEDO | basic_word | 그럼에도 */
static const uint32_t dict_seq_09[] = { R, M, F, J, A, D, P, E, H };
/* BASIC_GEUDERO | basic_word | 그대로 */
static const uint32_t dict_seq_10[] = { R, M, E, O, F, H };
/* BASIC_GAPJAGI | basic_word | 갑자기 */
static const uint32_t dict_seq_11[] = { R, K, Q, W, K, R, L };
/* BASIC_WANJEONHI | basic_word | 완전히 */
static const uint32_t dict_seq_12[] = { D, H, K, S, W, J, S, G, L };
/* BASIC_JOYONGHI | basic_word | 조용히 */
static const uint32_t dict_seq_13[] = { W, H, D, Y, D, G, L };
/* BASIC_DOEEOT | basic_word | 되었 */
static const uint32_t dict_seq_14[] = { E, H, L, D, J, LS(T) };
/* BASIC_GEUNDE | basic_word | 근데 */
static const uint32_t dict_seq_15[] = { R, M, S, E, P };
/* BASIC_GEUTTAE | basic_word | 그때 */
static const uint32_t dict_seq_16[] = { R, M, LS(E), O };
/* CONN_GEDAGA | connective | 게다가 */
static const uint32_t dict_seq_17[] = { R, P, E, K, R, K };
/* CONN_GEULIGO | connective | 그리고 */
static const uint32_t dict_seq_18[] = { R, M, F, L, R, H };
/* CONN_GEUREOJA | connective | 그러자 */
static const uint32_t dict_seq_19[] = { R, M, F, J, W, K };
/* CONN_GEUREOGI | connective | 그러기 */
static const uint32_t dict_seq_20[] = { R, M, F, J, R, L };
/* CONN_GEUREOTJI | connective | 그렇지 */
static const uint32_t dict_seq_21[] = { R, M, F, J, G, W, L };
/* CONN_HAJIMAN | connective | 하지만 */
static const uint32_t dict_seq_22[] = { G, K, W, L, A, K, S };
/* TAIL_YEOTDA | tail | 였다 */
static const uint32_t dict_seq_23[] = { D, U, LS(T), E, K };
/* TAIL_EOPDA | tail | 없다 */
static const uint32_t dict_seq_24[] = { D, J, Q, T, E, K };
/* TAIL_EOTDA | tail | 었다 */
static const uint32_t dict_seq_25[] = { D, J, LS(T), E, K };
/* TAIL_ATDA | tail | 았다 */
static const uint32_t dict_seq_26[] = { D, K, LS(T), E, K };
/* TAIL_IEOTDA | tail | 이었다 */
static const uint32_t dict_seq_27[] = { D, L, D, J, LS(T), E, K };
/* TAIL_EOSSEOTDA | tail | 었었다 */
static const uint32_t dict_seq_28[] = { D, J, LS(T), D, J, LS(T), E, K };
/* TAIL_ITDA | tail | 있다 */
static const uint32_t dict_seq_29[] = { D, L, LS(T), E, K };
/* TAIL_EDA | tail | 에다 */
static const uint32_t dict_seq_30[] = { D, P, E, K };
/* TAIL_HAETDA | tail | 했다 */
static const uint32_t dict_seq_31[] = { G, O, LS(T), E, K };
/* TAIL_DWAETDA | tail | 됐다 */
static const uint32_t dict_seq_32[] = { E, H, O, LS(T), E, K };
/* TAIL_NEUNDE | tail | 는데 */
static const uint32_t dict_seq_33[] = { S, M, S, E, P };
/* TAIL_EULJIDO | tail | 을지도 */
static const uint32_t dict_seq_34[] = { D, M, F, W, L, E, H };
/* TAIL_EOJYEOTDA | tail | 어졌다 */
static const uint32_t dict_seq_35[] = { D, J, W, U, LS(T), E, K };
/* TAIL_JIMAN | tail | 지만 */
static const uint32_t dict_seq_36[] = { W, L, A, K, S };
/* TAIL_SEUMNIDA | tail | 습니다 */
static const uint32_t dict_seq_37[] = { T, M, Q, S, L, E, K };
/* TAIL_EOSSEUMYEON | tail | 었으면 */
static const uint32_t dict_seq_38[] = { D, J, LS(T), D, M, A, U, S };
/* TAIL_HANEUNGE | tail | 하는게 */
static const uint32_t dict_seq_39[] = { G, K, S, M, S, R, P };
/* TAIL_ONEUNGE | tail | 오는게 */
static const uint32_t dict_seq_40[] = { D, H, S, M, S, R, P };
/* TAIL_GANEUNGE | tail | 가는게 */
static const uint32_t dict_seq_41[] = { R, K, S, M, S, R, P };

static const struct cornix_steno_dictionary_entry entries[] = {
    { .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_J)), .keys = dict_seq_00, .key_count = (uint16_t)(sizeof(dict_seq_00) / sizeof(dict_seq_00[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_J) | CST_ROLE_BIT(CST_R_F_DOUBLE)), .keys = dict_seq_01, .key_count = (uint16_t)(sizeof(dict_seq_01) / sizeof(dict_seq_01[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_02, .key_count = (uint16_t)(sizeof(dict_seq_02) / sizeof(dict_seq_02[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_03, .key_count = (uint16_t)(sizeof(dict_seq_03) / sizeof(dict_seq_03[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_04, .key_count = (uint16_t)(sizeof(dict_seq_04) / sizeof(dict_seq_04[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_05, .key_count = (uint16_t)(sizeof(dict_seq_05) / sizeof(dict_seq_05[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_06, .key_count = (uint16_t)(sizeof(dict_seq_06) / sizeof(dict_seq_06[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_07, .key_count = (uint16_t)(sizeof(dict_seq_07) / sizeof(dict_seq_07[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_08, .key_count = (uint16_t)(sizeof(dict_seq_08) / sizeof(dict_seq_08[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_09, .key_count = (uint16_t)(sizeof(dict_seq_09) / sizeof(dict_seq_09[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_F_R)), .keys = dict_seq_10, .key_count = (uint16_t)(sizeof(dict_seq_10) / sizeof(dict_seq_10[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_J) | CST_ROLE_BIT(CST_R_I_DOUBLE)), .keys = dict_seq_11, .key_count = (uint16_t)(sizeof(dict_seq_11) / sizeof(dict_seq_11[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_H)), .keys = dict_seq_12, .key_count = (uint16_t)(sizeof(dict_seq_12) / sizeof(dict_seq_12[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_J) | CST_ROLE_BIT(CST_R_F_H)), .keys = dict_seq_13, .key_count = (uint16_t)(sizeof(dict_seq_13) / sizeof(dict_seq_13[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_I_NG)), .keys = dict_seq_14, .key_count = (uint16_t)(sizeof(dict_seq_14) / sizeof(dict_seq_14[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_15, .key_count = (uint16_t)(sizeof(dict_seq_15) / sizeof(dict_seq_15[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_F_D) | CST_ROLE_BIT(CST_R_F_DOUBLE)), .keys = dict_seq_16, .key_count = (uint16_t)(sizeof(dict_seq_16) / sizeof(dict_seq_16[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_D) | CST_ROLE_BIT(CST_R_I_DOUBLE)), .keys = dict_seq_17, .key_count = (uint16_t)(sizeof(dict_seq_17) / sizeof(dict_seq_17[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_I_DOUBLE)), .keys = dict_seq_18, .key_count = (uint16_t)(sizeof(dict_seq_18) / sizeof(dict_seq_18[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_J)), .keys = dict_seq_19, .key_count = (uint16_t)(sizeof(dict_seq_19) / sizeof(dict_seq_19[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_I_DOUBLE)), .keys = dict_seq_20, .key_count = (uint16_t)(sizeof(dict_seq_20) / sizeof(dict_seq_20[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_I_G) | CST_ROLE_BIT(CST_R_I_R) | CST_ROLE_BIT(CST_R_F_J)), .keys = dict_seq_21, .key_count = (uint16_t)(sizeof(dict_seq_21) / sizeof(dict_seq_21[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_I_H) | CST_ROLE_BIT(CST_R_I_J) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_22, .key_count = (uint16_t)(sizeof(dict_seq_22) / sizeof(dict_seq_22[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_23, .key_count = (uint16_t)(sizeof(dict_seq_23) / sizeof(dict_seq_23[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_24, .key_count = (uint16_t)(sizeof(dict_seq_24) / sizeof(dict_seq_24[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_25, .key_count = (uint16_t)(sizeof(dict_seq_25) / sizeof(dict_seq_25[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_26, .key_count = (uint16_t)(sizeof(dict_seq_26) / sizeof(dict_seq_26[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_VEXT_L) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_27, .key_count = (uint16_t)(sizeof(dict_seq_27) / sizeof(dict_seq_27[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_VEXT_L) | CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_28, .key_count = (uint16_t)(sizeof(dict_seq_28) / sizeof(dict_seq_28[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_VEXT_L) | CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_29, .key_count = (uint16_t)(sizeof(dict_seq_29) / sizeof(dict_seq_29[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_I_NG) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_30, .key_count = (uint16_t)(sizeof(dict_seq_30) / sizeof(dict_seq_30[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_H) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_31, .key_count = (uint16_t)(sizeof(dict_seq_31) / sizeof(dict_seq_31[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_DOUBLE) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_32, .key_count = (uint16_t)(sizeof(dict_seq_32) / sizeof(dict_seq_32[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_VEXT_L) | CST_ROLE_BIT(CST_R_F_N)), .keys = dict_seq_33, .key_count = (uint16_t)(sizeof(dict_seq_33) / sizeof(dict_seq_33[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_J) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_34, .key_count = (uint16_t)(sizeof(dict_seq_34) / sizeof(dict_seq_34[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_J) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_35, .key_count = (uint16_t)(sizeof(dict_seq_35) / sizeof(dict_seq_35[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_J) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_36, .key_count = (uint16_t)(sizeof(dict_seq_36) / sizeof(dict_seq_36[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_VEXT_L) | CST_ROLE_BIT(CST_R_F_S) | CST_ROLE_BIT(CST_R_F_D)), .keys = dict_seq_37, .key_count = (uint16_t)(sizeof(dict_seq_37) / sizeof(dict_seq_37[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_VEXT_L) | CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_F_M)), .keys = dict_seq_38, .key_count = (uint16_t)(sizeof(dict_seq_38) / sizeof(dict_seq_38[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_H) | CST_ROLE_BIT(CST_R_F_N) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_39, .key_count = (uint16_t)(sizeof(dict_seq_39) / sizeof(dict_seq_39[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_NG) | CST_ROLE_BIT(CST_R_F_N) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_40, .key_count = (uint16_t)(sizeof(dict_seq_40) / sizeof(dict_seq_40[0])) },
    { .role_mask = (CST_ROLE_BIT(CST_R_F_DOUBLE) | CST_ROLE_BIT(CST_R_F_N) | CST_ROLE_BIT(CST_R_F_G)), .keys = dict_seq_41, .key_count = (uint16_t)(sizeof(dict_seq_41) / sizeof(dict_seq_41[0])) },
};

uint64_t cornix_steno_dictionary_normalize_mask(uint64_t role_mask) {
    const uint64_t vext_l = CST_ROLE_BIT(CST_R_VEXT_L);
    const uint64_t vext_r = CST_ROLE_BIT(CST_R_VEXT_R);
    const uint64_t vext = role_mask & CST_VEXT_MASK;
    if ((role_mask & CST_BASE_VOWEL_MASK) == 0 &&
        (vext == vext_l || vext == vext_r)) {
        role_mask = (role_mask & ~CST_VEXT_MASK) | vext_l;
    }
    return role_mask;
}

const struct cornix_steno_dictionary_entry *
cornix_steno_dictionary_lookup(uint64_t role_mask) {
    const uint64_t normalized = cornix_steno_dictionary_normalize_mask(role_mask);
    for (size_t i = 0; i < sizeof(entries) / sizeof(entries[0]); i++) {
        if (entries[i].role_mask == normalized) return &entries[i];
    }
    return NULL;
}

bool cornix_steno_dictionary_has_exact(uint64_t role_mask) {
    return cornix_steno_dictionary_lookup(role_mask) != NULL;
}

size_t cornix_steno_dictionary_count(void) {
    return sizeof(entries) / sizeof(entries[0]);
}
