/* Auto-generated by tools/generate_steno_quick.py. */
/* SPDX-License-Identifier: MIT */

#include <stddef.h>
#include <stdint.h>
#include <cornix_steno/quick.h>
#include <cornix_steno/roles.h>

static const struct cornix_steno_quick_entry entries[] = {
    { .slot = "M0", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_EU)), .macro_slot = CST_QUICK_M0 },
    { .slot = "M1", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_O)), .macro_slot = CST_QUICK_M1 },
    { .slot = "M2", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_U)), .macro_slot = CST_QUICK_M2 },
    { .slot = "M3", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_A)), .macro_slot = CST_QUICK_M3 },
    { .slot = "M4", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_I)), .macro_slot = CST_QUICK_M4 },
    { .slot = "M5", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_EO)), .macro_slot = CST_QUICK_M5 },
    { .slot = "M6", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_A)), .macro_slot = CST_QUICK_M6 },
    { .slot = "M7", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_EO)), .macro_slot = CST_QUICK_M7 },
    { .slot = "M8", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_L) | CST_ROLE_BIT(CST_R_V_I)), .macro_slot = CST_QUICK_M8 },
    { .slot = "M9", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_O)), .macro_slot = CST_QUICK_M9 },
    { .slot = "M10", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_U)), .macro_slot = CST_QUICK_M10 },
    { .slot = "M11", .role_mask = (CST_ROLE_BIT(CST_R_ABBR_R) | CST_ROLE_BIT(CST_R_V_EU)), .macro_slot = CST_QUICK_M11 },
};

const struct cornix_steno_quick_entry *cornix_steno_quick_lookup(uint64_t role_mask) {
    for (size_t i=0; i<sizeof(entries)/sizeof(entries[0]); i++)
        if (entries[i].role_mask == role_mask) return &entries[i];
    return NULL;
}

size_t cornix_steno_quick_count(void) { return sizeof(entries)/sizeof(entries[0]); }
