#pragma once
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#define CONFIG_CORNIX_STENO 1
#define CONFIG_CORNIX_STENO_MAX_POSITIONS 50
#define CONFIG_CORNIX_STENO_CHORD_SETTLE_MS 40
#define CONFIG_CORNIX_STENO_KEYUP_CORRECTION_MS 50
#define CONFIG_CORNIX_STENO_FINAL_ROLL_MS 90
#define CONFIG_CORNIX_STENO_LATE_TAP_MAX_MS 120
#define CONFIG_CORNIX_STENO_SOLO_DOUBLE_MS 230
#define CONFIG_CORNIX_STENO_DUAL_TAPPING_TERM_MS 150
#define CONFIG_CORNIX_STENO_OUTPUT_QUEUE_SIZE 256
#define CONFIG_CORNIX_STENO_OUTPUT_HOLD_MS 4
#define CONFIG_CORNIX_STENO_OUTPUT_GAP_MS 4
#define CONFIG_CORNIX_STENO_DICTIONARY 1
#define CONFIG_CORNIX_STENO_LED 1
#define CONFIG_CORNIX_STENO_LED_ENTRY_FLASH_MS 600
#define CONFIG_CORNIX_STENO_LED_REASSERT_DELAY_MS 40
#define CONFIG_CORNIX_STENO_LED_CATEGORY_FLASH_MS 350
#define CONFIG_RGBLED_WIDGET_LED_COUNT 2
#define CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL 20
#define CONFIG_RGBLED_WIDGET_CONN_SHOW_USB 0
#define CONFIG_ZMK_LOG_LEVEL 3
#define CONFIG_ZMK_BEHAVIOR_METADATA 0
#define CONFIG_ZMK_SPLIT 1
#define CONFIG_ZMK_SPLIT_ROLE_CENTRAL 1
#define CONFIG_ZMK_SPLIT_BLE 1
#define CONFIG_ZMK_BATTERY_REPORTING 1
#define CONFIG_ZMK_BLE 1
#define CONFIG_BT_HAS_HCI_VS 1
#define CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL 1
#define CONFIG_KERNEL_INIT_PRIORITY_DEFAULT 50
#define CONFIG_APPLICATION_INIT_PRIORITY 90
#define IS_ENABLED(x) (x)
#define DT_HAS_COMPAT_STATUS_OKAY(x) 1
#define DT_INST_PROP(n, prop) 0
#define DT_INST_PROP_OR(n, prop, default_value) (default_value)
#define DT_INST_FOREACH_STATUS_OKAY(fn) fn(0)
#define POST_KERNEL 0
#define APPLICATION 0
