#pragma once
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#define CONFIG_CORNIX_STENO_MAX_POSITIONS 50
#define CONFIG_CORNIX_STENO_CHORD_SETTLE_MS 40
#define CONFIG_CORNIX_STENO_KEYUP_CORRECTION_MS 50
#define CONFIG_CORNIX_STENO_LATE_TAP_MAX_MS 120
#define CONFIG_CORNIX_STENO_SOLO_DOUBLE_MS 230
#define CONFIG_CORNIX_STENO_DUAL_TAPPING_TERM_MS 200
#define CONFIG_CORNIX_STENO_DICTIONARY 1
#define CONFIG_ZMK_LOG_LEVEL 3
#define CONFIG_APPLICATION_INIT_PRIORITY 90
#define IS_ENABLED(x) (x)
#define APPLICATION 0
