#!/usr/bin/env python3
"""Generate four editable Cornix quick-abbreviation slots."""
from __future__ import annotations
import argparse, csv
from pathlib import Path
from generate_steno_dictionary import text_to_keys
ROLE_ENUMS = {
    "ABBR_L":"CST_R_ABBR_L", "ABBR_R":"CST_R_ABBR_R",
    "V_O":"CST_R_V_O", "V_EU":"CST_R_V_EU", "V_U":"CST_R_V_U",
    "V_A":"CST_R_V_A", "V_I":"CST_R_V_I", "V_EO":"CST_R_V_EO",
}

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('input',type=Path); ap.add_argument('output',type=Path); a=ap.parse_args()
    rows=[]
    with a.input.open(encoding='utf-8',newline='') as f:
        for ln,row in enumerate(csv.reader(f,delimiter='\t'),1):
            if not row or row[0].lstrip().startswith('#'): continue
            if len(row)!=3: raise ValueError(f'{a.input}:{ln}: expected slot, output, roles')
            slot,output,rt=(x.strip() for x in row)
            roles=tuple(x.strip() for x in rt.split('+') if x.strip())
            if not slot or not roles: raise ValueError(f'{a.input}:{ln}: missing slot or roles')
            bad=[r for r in roles if r not in ROLE_ENUMS]
            if bad: raise ValueError(f'{a.input}:{ln}: unknown roles {bad}')
            if len(set(roles))!=len(roles): raise ValueError(f'{a.input}:{ln}: duplicate role')
            rows.append((slot,output,roles,text_to_keys(output) if output else []))
    if len(rows)!=4: raise ValueError(f'expected exactly 4 quick slots, found {len(rows)}')
    seen=set()
    for slot,output,roles,keys in rows:
        sig=tuple(sorted(roles))
        if sig in seen: raise ValueError(f'duplicate quick exact mask: {slot}')
        seen.add(sig)
    out=['/* Auto-generated by tools/generate_steno_quick.py. */','/* SPDX-License-Identifier: MIT */','',
         '#include <stddef.h>','#include <stdint.h>','#include <dt-bindings/zmk/keys.h>',
         '#include <cornix_steno/quick.h>','#include <cornix_steno/roles.h>','']
    names=[]
    for i,(slot,output,roles,keys) in enumerate(rows):
        name=f'quick_seq_{i:02d}'
        names.append(name if keys else 'NULL')
        if keys:
            out += [f'/* {slot}: {output} */',f'static const uint32_t {name}[] = {{ {", ".join(keys)} }};']
    out += ['', 'static const struct cornix_steno_quick_entry entries[] = {']
    for (slot,output,roles,keys),name in zip(rows,names):
        mask=' | '.join(f'CST_ROLE_BIT({ROLE_ENUMS[r]})' for r in roles)
        count=f'(uint16_t)(sizeof({name}) / sizeof({name}[0]))' if keys else '0'
        out.append(f'    {{ .slot = "{slot}", .role_mask = ({mask}), .keys = {name}, .key_count = {count} }},')
    out += ['};','',
            'const struct cornix_steno_quick_entry *cornix_steno_quick_lookup(uint64_t role_mask) {',
            '    for (size_t i=0; i<sizeof(entries)/sizeof(entries[0]); i++)',
            '        if (entries[i].role_mask == role_mask) return &entries[i];',
            '    return NULL;','}','',
            'size_t cornix_steno_quick_count(void) { return sizeof(entries)/sizeof(entries[0]); }','']
    a.output.parent.mkdir(parents=True,exist_ok=True)
    a.output.write_text('\n'.join(out),encoding='utf-8',newline='\n')
    print(f'generated {len(rows)} quick slots -> {a.output}')
if __name__=='__main__': main()
