#!/usr/bin/env python3
"""Generate twelve Cornix quick-abbreviation trigger slots.

The input chords are fixed STENO exact masks. Output text is owned by twelve
normal ZMK macro nodes (quick_0 through quick_11) in config/cornix.keymap so
Nick Coutsos' ZMK Keymap Editor can edit the macro bodies visually.
"""
from __future__ import annotations
import argparse, csv
from pathlib import Path

ROLE_ENUMS = {
    "ABBR_L":"CST_R_ABBR_L", "ABBR_R":"CST_R_ABBR_R",
    "V_O":"CST_R_V_O", "V_EU":"CST_R_V_EU", "V_U":"CST_R_V_U",
    "V_A":"CST_R_V_A", "V_I":"CST_R_V_I", "V_EO":"CST_R_V_EO",
}
SLOT_ENUMS = {
    "M0":"CST_QUICK_M0",
    "M1":"CST_QUICK_M1",
    "M2":"CST_QUICK_M2",
    "M3":"CST_QUICK_M3",
    "M4":"CST_QUICK_M4",
    "M5":"CST_QUICK_M5",
    "M6":"CST_QUICK_M6",
    "M7":"CST_QUICK_M7",
    "M8":"CST_QUICK_M8",
    "M9":"CST_QUICK_M9",
    "M10":"CST_QUICK_M10",
    "M11":"CST_QUICK_M11",
}


def main() -> None:
    ap=argparse.ArgumentParser()
    ap.add_argument('input',type=Path)
    ap.add_argument('output',type=Path)
    a=ap.parse_args()
    rows=[]
    with a.input.open(encoding='utf-8',newline='') as f:
        for ln,row in enumerate(csv.reader(f,delimiter='\t'),1):
            if not row or row[0].lstrip().startswith('#'):
                continue
            if len(row)!=3:
                raise ValueError(f'{a.input}:{ln}: expected slot, legacy-output, roles')
            slot,legacy_output,rt=(x.strip() for x in row)
            if slot not in SLOT_ENUMS:
                raise ValueError(f'{a.input}:{ln}: unknown slot {slot!r}')
            if legacy_output:
                raise ValueError(
                    f'{a.input}:{ln}: output is owned by the ZMK macro quick_{slot[1:]}; '
                    'leave the trigger TSV output column blank')
            roles=tuple(x.strip() for x in rt.split('+') if x.strip())
            if not roles:
                raise ValueError(f'{a.input}:{ln}: missing roles')
            bad=[r for r in roles if r not in ROLE_ENUMS]
            if bad:
                raise ValueError(f'{a.input}:{ln}: unknown roles {bad}')
            if len(set(roles))!=len(roles):
                raise ValueError(f'{a.input}:{ln}: duplicate role')
            rows.append((slot,roles))
    if len(rows)!=12:
        raise ValueError(f'expected exactly 12 quick slots, found {len(rows)}')
    if set(slot for slot,_ in rows)!=set(SLOT_ENUMS):
        raise ValueError('quick slot set is incomplete')
    seen=set()
    for slot,roles in rows:
        sig=tuple(sorted(roles))
        if sig in seen:
            raise ValueError(f'duplicate quick exact mask: {slot}')
        seen.add(sig)

    out=[
        '/* Auto-generated by tools/generate_steno_quick.py. */',
        '/* SPDX-License-Identifier: MIT */','',
        '#include <stddef.h>','#include <stdint.h>',
        '#include <cornix_steno/quick.h>',
        '#include <cornix_steno/roles.h>','',
        'static const struct cornix_steno_quick_entry entries[] = {',
    ]
    for slot,roles in rows:
        mask=' | '.join(f'CST_ROLE_BIT({ROLE_ENUMS[r]})' for r in roles)
        out.append(
            f'    {{ .slot = "{slot}", .role_mask = ({mask}), '
            f'.macro_slot = {SLOT_ENUMS[slot]} }},')
    out += [
        '};','',
        'const struct cornix_steno_quick_entry *cornix_steno_quick_lookup(uint64_t role_mask) {',
        '    for (size_t i=0; i<sizeof(entries)/sizeof(entries[0]); i++)',
        '        if (entries[i].role_mask == role_mask) return &entries[i];',
        '    return NULL;','}','',
        'size_t cornix_steno_quick_count(void) { return sizeof(entries)/sizeof(entries[0]); }','',
    ]
    a.output.parent.mkdir(parents=True,exist_ok=True)
    a.output.write_text('\n'.join(out),encoding='utf-8',newline='\n')
    print(f'generated {len(rows)} GUI-macro trigger slots -> {a.output}')

if __name__=='__main__':
    main()
